# Generated by Django 4.2.23 on 2025-08-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
