# Generated by Django 4.2.23 on 2025-08-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_product_images_service_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of what this category includes', null=True),
        ),
    ]
