# Generated by Django 4.2.23 on 2025-08-15 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0007_add_like_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes from the user', null=True)),
                ('business_response', models.TextField(blank=True, help_text='Response from the business owner', null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='rating_between_1_and_5',
        ),
        # Keep BusinessLike.id as UUID (do not convert to bigint)
        migrations.AlterField(
            model_name='businesslike',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_reviews', to=settings.AUTH_USER_MODEL),
        ),
        # Keep ReviewLike.id as UUID (do not convert to bigint)
        migrations.AlterField(
            model_name='reviewlike',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True),
        ),
        migrations.AddField(
            model_name='photorequest',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_requests', to='business.business'),
        ),
        migrations.AddField(
            model_name='photorequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='photorequest',
            unique_together={('business', 'user')},
        ),
    ]
