# Generated by Django 4.2.23 on 2025-09-08 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_add_subcategories_support'),
        ('business', '0010_alter_businesslike_id_alter_reviewlike_id'),
    ]

    operations = [
    ]
