# Generated by Django 4.2.23 on 2025-09-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_address_and_church_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_currency',
            field=models.CharField(default='KSH', max_length=3),
        ),
    ]
