# Generated by Django 4.2.23 on 2025-09-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_add_slug_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('products', 'Products'), ('services', 'Services'), ('both', 'Both Products and Services')], default='both', help_text='Type of business: Products, Services, or Both', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp number for direct messaging', max_length=20, null=True),
        ),
    ]
